### ISSUE TITLE
Feature: User can draw on canvas

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#1]
## ⚙️ Feature

User can draw on canvas

## 📐 Functionality

User will be able to see their strokes show up on a blank canvas

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/32401196/147500818-ff30dbcc-9ef9-4986-bba8-676e42ef41cc.png)
![image](https://user-images.githubusercontent.com/32401196/147500840-aded784e-6e17-4ad1-961d-345382f1f4ea.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for navbar
- [x] Create component to select art tools
- [x] create component to hold canvas
- [x] create component for drawer

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
