### ISSUE TITLE
Feature: User can browse drawings

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#11]
## ⚙️ Feature

user can browse drawings

## 📐 Functionality

user can browse gallery of drawings sorted by month/day/year

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/32401196/147821257-fea7b14c-5d83-4c48-b3a7-221fc84a3ae7.png)
![image](https://user-images.githubusercontent.com/32401196/147821279-8895820d-e188-4155-aacf-dc67f7a0406f.png)
![image](https://user-images.githubusercontent.com/32401196/147821293-d8f1e283-b91a-4611-8b84-0759cc441448.png)
![image](https://user-images.githubusercontent.com/32401196/147821301-760406eb-f8cb-4d10-9023-18295ba7a8e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] add handler for '/api/doodles/:fullDate' (ISO-8601 format, YYYY-MM-DD)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create View page to view specific drawing
- [x] create Browse page to view gallery of all drawings

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
