### ISSUE TITLE
Feature: User can view own/other people’s profiles

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#13]
## ⚙️ Feature

User can view own/other people’s profiles

## 📐 Functionality

User can see all info about user including their profile picture, username, location, bio, submissions

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/32401196/147896460-9d7f24c5-0aee-43eb-8243-2dbf4623b154.png)
![image](https://user-images.githubusercontent.com/32401196/147896466-0457939a-9a4e-4bc0-ac17-1e649ab4b436.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] add handler for '/api/user/:userId'
- [x] add handler for '/api/userDoodles/:userId'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create a profile page
- [x] clicking on username on view page will link to profile page
- [x] left section artist info section
- [x] right section submissions/favorites tabs
- [x] load all of user's doodles on to page when on submissions tab

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
