### ISSUE TITLE
Feature: User can create a drawing

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#2]
## ⚙️ Feature

User can create a drawing

## 📐 Functionality

User can press the create button to submit drawing to be stored on the backend.

## 🖼️ Wireframes

will include screenshots of httpie for this one

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include table creation for users, likes, favorites, and doodles

### ☁️ Server

- [x] Update `server/index.js` to handle POST request to '/api/doodle'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] onSubmit, make POST request to ('/api/doodle')

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
