### ISSUE TITLE
Feature: User can update drawing

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#3]
## ⚙️ Feature

User can update drawing

## 📐 Functionality

User will be able to edit existing drawing and save update in backend.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/32401196/147704433-c62970fe-0467-4312-97ed-832b9206d07e.png)
![image](https://user-images.githubusercontent.com/32401196/147704458-befce5c5-f685-4a62-9a62-3d66e97f434c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] add handler for get '/api/doodle/:id'
- [x] add handler for put '/api/doodle/:id'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] create edit page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
