### ISSUE TITLE
Feature: User can see timer for current drawing session

### ISSUE THREAD

**Issue by byu014** [byu014/a-doodle-in-time#9]
## ⚙️ Feature

User can see timer for current drawing session

## 📐 Functionality

User can see timer left for today's drawing session. Can only work on today's submission while timer is not over.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update index.js to have handler for get '/api/doodle/today/:userId'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for timer
- [x] create a component for redirect
- [x] make request to '/api/doodle/today/:userId' 
- [x] if successful request redirect user to edit page for their drawing of today

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
